version: 2
jobs:
  build:
    docker:
      - image: aparker/circleci-dotnet-mono:latest
    steps:
      - checkout
      - run: msbuild DemoCricleCi/DemoCricleCi/DemoCricleCi.csproj /t:Restore
      - run: msbuild DemoCricleCi/DemoCricleCi/DemoCricleCi.csproj /t:Build
      - run: nuget pack DemoCricleCi.nuspec
