version: 2
jobs:
  build:
    docker:
      - image: aparker/circleci-dotnet-mono:latest
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OUTPUT: 1
    steps:
      - run: msbuild DemoCricleCi/DemoCricleCi/DemoCricleCi.csproj /t:Restore
      - run: msbuild DemoCricleCi/DemoCricleCi/DemoCricleCi.csproj /p:Configuration=Release
