version: 2
jobs:
  build:
    docker:
      - image: aparker/circleci-dotnet-mono:latest
    steps:
      - run: msbuild DemoCricleCi/DemoCricleCi/DemoCricleCi.csproj /t:Restore
      - run: msbuild DemoCricleCi/DemoCricleCi/DemoCricleCi.csproj /p:Configuration=Release
